language: c
sudo: false

script:
  - ./prepare.sh texlive.tar.xz

after_success:
  - ls -lh texlive.tar.xz

deploy:
  provider: releases
  api_key:
    secure: D14Yidjgzfs/M56SuVbhoxp5mHnWwfyQD8YauBVwRqLgrk4RKleSPNZHAP/J5qzw+cSuqVaOUoga01vAMI3tdTLUDtmxvA7KcDwZfx8Cb9s0nBWL7dCrc9riwMnJxJfh7fCyK6JP/fWX+WeDwIGg3ZG/cRfmbDXXZ7kvzcd2dqg=
  skip_cleanup: true
  file:
    - texlive.tar.xz
  on:
    tags: true
