language: c
sudo: false

script:
  - ./prepare.sh texlive.tar.xz

after_success:
  - ls -lh texlive.tar.xz

deploy:
  provider: releases
  api_key:
    secure: bUe/Q1Gcl8NNmtOOAXzu7NgWYOwfVJvP3+pRw8RuTgZElT+UpA2ncdUyBFsBzjDzkirFXcIsJSjVd/qzcMv8kEKxL5XgauwfyK6W6NayHpxVCOPCLncgHaatT1TukG8XRbZh4h343XuhSaUA9gNTxglqStbuS3n+Il7fuxh8j1Q=
  skip_cleanup: true
  file:
    - texlive.tar.xz
  on:
    tags: true
    repo: urdh/texlive-blob
